### ISSUE TITLE
How do we configure this? and where to add DNS data?

### ISSUE THREAD

**Issue by seansan** [mygento/sentry#1]
How do we configure this? and where to add DNS data?

Super thanks

**Comment by luckyraul** [comment]
Admin

**Comment by seansan** [comment]
do you mean system->configuration->admin?

after installing 1.1 version (FTP upload)

Magento 1.9.4.5 we dont see any options

**Comment by luckyraul** [comment]
install via composer, it won't work without it

**Comment by seansan** [comment]
is it possible to package it simply as zip? we dont run composer on M1 ....

**Comment by luckyraul** [comment]
1) today is 2020, composer is vital
2) It requires sentry sdk - available via composer
3) M1 core works pretty well from composer, as vendor dependency.
